export interface Employee {
    id: number;
    username: string;
    firstName: string;
    lastName: string;
    email: string;
    birthDate: Date;
    basicSalary: number;
    status: string;
    group: string;
    description: Date;
}

export const Employees: Employee[] = [
    {
        id: 1,
        username: 'budi.santoso',
        firstName: 'Budi',
        lastName: 'Santoso',
        email: 'budi.santoso@example.com',
        birthDate: new Date('1985-02-14'),
        basicSalary: 5000000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 2,
        username: 'siti.marlina',
        firstName: 'Siti',
        lastName: 'Marlina',
        email: 'siti.marlina@example.com',
        birthDate: new Date('1990-07-25'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 3,
        username: 'agus.prasetyo',
        firstName: 'Agus',
        lastName: 'Prasetyo',
        email: 'agus.prasetyo@example.com',
        birthDate: new Date('1982-03-10'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 4,
        username: 'dian.purnama',
        firstName: 'Dian',
        lastName: 'Purnama',
        email: 'dian.purnama@example.com',
        birthDate: new Date('1987-11-05'),
        basicSalary: 5200000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 5,
        username: 'yusuf.hidayat',
        firstName: 'Yusuf',
        lastName: 'Hidayat',
        email: 'yusuf.hidayat@example.com',
        birthDate: new Date('1992-08-30'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 6,
        username: 'ratna.sari',
        firstName: 'Ratna',
        lastName: 'Sari',
        email: 'ratna.sari@example.com',
        birthDate: new Date('1989-01-15'),
        basicSalary: 5100000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 7,
        username: 'andi.wijaya',
        firstName: 'Andi',
        lastName: 'Wijaya',
        email: 'andi.wijaya@example.com',
        birthDate: new Date('1991-05-21'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 8,
        username: 'wulan.septiani',
        firstName: 'Wulan',
        lastName: 'Septiani',
        email: 'wulan.septiani@example.com',
        birthDate: new Date('1986-04-09'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 9,
        username: 'teguh.susanto',
        firstName: 'Teguh',
        lastName: 'Susanto',
        email: 'teguh.susanto@example.com',
        birthDate: new Date('1988-12-12'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 10,
        username: 'lisa.sukmawati',
        firstName: 'Lisa',
        lastName: 'Sukmawati',
        email: 'lisa.sukmawati@example.com',
        birthDate: new Date('1993-09-17'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 11,
        username: 'rina.yulianti',
        firstName: 'Rina',
        lastName: 'Yulianti',
        email: 'rina.yulianti@example.com',
        birthDate: new Date('1984-06-18'),
        basicSalary: 5100000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 12,
        username: 'eko.supriyadi',
        firstName: 'Eko',
        lastName: 'Supriyadi',
        email: 'eko.supriyadi@example.com',
        birthDate: new Date('1995-02-23'),
        basicSalary: 5200000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 13,
        username: 'indah.putri',
        firstName: 'Indah',
        lastName: 'Putri',
        email: 'indah.putri@example.com',
        birthDate: new Date('1988-09-12'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 14,
        username: 'hari.susilo',
        firstName: 'Hari',
        lastName: 'Susilo',
        email: 'hari.susilo@example.com',
        birthDate: new Date('1991-01-06'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 15,
        username: 'sari.rahmawati',
        firstName: 'Sari',
        lastName: 'Rahmawati',
        email: 'sari.rahmawati@example.com',
        birthDate: new Date('1987-10-28'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 16,
        username: 'yudi.kurniawan',
        firstName: 'Yudi',
        lastName: 'Kurniawan',
        email: 'yudi.kurniawan@example.com',
        birthDate: new Date('1992-11-15'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 17,
        username: 'lina.febrianti',
        firstName: 'Lina',
        lastName: 'Febrianti',
        email: 'lina.febrianti@example.com',
        birthDate: new Date('1985-05-02'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 18,
        username: 'taufik.rahman',
        firstName: 'Taufik',
        lastName: 'Rahman',
        email: 'taufik.rahman@example.com',
        birthDate: new Date('1990-03-27'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 19,
        username: 'dewi.suryani',
        firstName: 'Dewi',
        lastName: 'Suryani',
        email: 'dewi.suryani@example.com',
        birthDate: new Date('1986-12-19'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 20,
        username: 'agus.santoso',
        firstName: 'Agus',
        lastName: 'Santoso',
        email: 'agus.santoso@example.com',
        birthDate: new Date('1989-07-09'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 21,
        username: 'fitri.rahayu',
        firstName: 'Fitri',
        lastName: 'Rahayu',
        email: 'fitri.rahayu@example.com',
        birthDate: new Date('1984-03-11'),
        basicSalary: 5200000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 22,
        username: 'joko.supriyanto',
        firstName: 'Joko',
        lastName: 'Supriyanto',
        email: 'joko.supriyanto@example.com',
        birthDate: new Date('1986-08-22'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 23,
        username: 'nurul.fadilah',
        firstName: 'Nurul',
        lastName: 'Fadilah',
        email: 'nurul.fadilah@example.com',
        birthDate: new Date('1991-02-05'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 24,
        username: 'tri.wibowo',
        firstName: 'Tri',
        lastName: 'Wibowo',
        email: 'tri.wibowo@example.com',
        birthDate: new Date('1989-04-16'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 25,
        username: 'aisyah.putri',
        firstName: 'Aisyah',
        lastName: 'Putri',
        email: 'aisyah.putri@example.com',
        birthDate: new Date('1985-11-03'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 26,
        username: 'ridwan.rahmad',
        firstName: 'Ridwan',
        lastName: 'Rahmad',
        email: 'ridwan.rahmad@example.com',
        birthDate: new Date('1992-09-14'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 27,
        username: 'ina.febriana',
        firstName: 'Ina',
        lastName: 'Febriana',
        email: 'ina.febriana@example.com',
        birthDate: new Date('1987-07-18'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 28,
        username: 'tono.rustam',
        firstName: 'Tono',
        lastName: 'Rustam',
        email: 'tono.rustam@example.com',
        birthDate: new Date('1990-10-20'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 29,
        username: 'mega.yulianti',
        firstName: 'Mega',
        lastName: 'Yulianti',
        email: 'mega.yulianti@example.com',
        birthDate: new Date('1986-05-30'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 30,
        username: 'hendri.susanto',
        firstName: 'Hendri',
        lastName: 'Susanto',
        email: 'hendri.susanto@example.com',
        birthDate: new Date('1989-12-07'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 31,
        username: 'sari.nuraini',
        firstName: 'Sari',
        lastName: 'Nuraini',
        email: 'sari.nuraini@example.com',
        birthDate: new Date('1987-01-24'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 32,
        username: 'fajar.prasetyo',
        firstName: 'Fajar',
        lastName: 'Prasetyo',
        email: 'fajar.prasetyo@example.com',
        birthDate: new Date('1990-02-15'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 33,
        username: 'lina.anggraeni',
        firstName: 'Lina',
        lastName: 'Anggraeni',
        email: 'lina.anggraeni@example.com',
        birthDate: new Date('1985-03-05'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 34,
        username: 'wahyu.susilo',
        firstName: 'Wahyu',
        lastName: 'Susilo',
        email: 'wahyu.susilo@example.com',
        birthDate: new Date('1989-04-18'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 35,
        username: 'nurhadi.rahman',
        firstName: 'Nurhadi',
        lastName: 'Rahman',
        email: 'nurhadi.rahman@example.com',
        birthDate: new Date('1991-05-22'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 36,
        username: 'yuni.setiawati',
        firstName: 'Yuni',
        lastName: 'Setiawati',
        email: 'yuni.setiawati@example.com',
        birthDate: new Date('1988-06-13'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 37,
        username: 'tri.astuti',
        firstName: 'Tri',
        lastName: 'Astuti',
        email: 'tri.astuti@example.com',
        birthDate: new Date('1990-07-19'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 38,
        username: 'eko.prabowo',
        firstName: 'Eko',
        lastName: 'Prabowo',
        email: 'eko.prabowo@example.com',
        birthDate: new Date('1987-08-29'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 39,
        username: 'rani.amelia',
        firstName: 'Rani',
        lastName: 'Amelia',
        email: 'rani.amelia@example.com',
        birthDate: new Date('1992-09-14'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 40,
        username: 'bayu.kusuma',
        firstName: 'Bayu',
        lastName: 'Kusuma',
        email: 'bayu.kusuma@example.com',
        birthDate: new Date('1985-10-10'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 41,
        username: 'fitria.ningsih',
        firstName: 'Fitria',
        lastName: 'Ningsih',
        email: 'fitria.ningsih@example.com',
        birthDate: new Date('1986-11-11'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 42,
        username: 'adi.kurniawan',
        firstName: 'Adi',
        lastName: 'Kurniawan',
        email: 'adi.kurniawan@example.com',
        birthDate: new Date('1990-12-12'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 43,
        username: 'dewi.rahayu',
        firstName: 'Dewi',
        lastName: 'Rahayu',
        email: 'dewi.rahayu@example.com',
        birthDate: new Date('1985-01-13'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 44,
        username: 'bambang.susilo',
        firstName: 'Bambang',
        lastName: 'Susilo',
        email: 'bambang.susilo@example.com',
        birthDate: new Date('1989-02-14'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 45,
        username: 'siti.nuraini',
        firstName: 'Siti',
        lastName: 'Nuraini',
        email: 'siti.nuraini@example.com',
        birthDate: new Date('1991-03-15'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 46,
        username: 'surya.setiawan',
        firstName: 'Surya',
        lastName: 'Setiawan',
        email: 'surya.setiawan@example.com',
        birthDate: new Date('1988-04-16'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 47,
        username: 'dini.astuti',
        firstName: 'Dini',
        lastName: 'Astuti',
        email: 'dini.astuti@example.com',
        birthDate: new Date('1990-05-17'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 48,
        username: 'joko.purnomo',
        firstName: 'Joko',
        lastName: 'Purnomo',
        email: 'joko.purnomo@example.com',
        birthDate: new Date('1987-06-18'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 49,
        username: 'nina.kusuma',
        firstName: 'Nina',
        lastName: 'Kusuma',
        email: 'nina.kusuma@example.com',
        birthDate: new Date('1992-07-19'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 50,
        username: 'budiawan.santoso',
        firstName: 'Budiawan',
        lastName: 'Santoso',
        email: 'budiawan.santoso@example.com',
        birthDate: new Date('1985-08-20'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 51,
        username: 'rini.perwita',
        firstName: 'Rini',
        lastName: 'Perwita',
        email: 'rini.perwita@example.com',
        birthDate: new Date('1986-09-21'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 52,
        username: 'adi.prabowo',
        firstName: 'Adi',
        lastName: 'Prabowo',
        email: 'adi.prabowo@example.com',
        birthDate: new Date('1990-10-22'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 53,
        username: 'nina.susanti',
        firstName: 'Nina',
        lastName: 'Susanti',
        email: 'nina.susanti@example.com',
        birthDate: new Date('1985-11-23'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 54,
        username: 'budi.santoso2',
        firstName: 'Budi',
        lastName: 'Santoso',
        email: 'budi.santoso2@example.com',
        birthDate: new Date('1989-12-24'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 55,
        username: 'sari.nurlita',
        firstName: 'Sari',
        lastName: 'Nurlita',
        email: 'sari.nurlita@example.com',
        birthDate: new Date('1991-01-25'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 56,
        username: 'agus.widodo',
        firstName: 'Agus',
        lastName: 'Widodo',
        email: 'agus.widodo@example.com',
        birthDate: new Date('1988-02-26'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 57,
        username: 'dewi.astuti',
        firstName: 'Dewi',
        lastName: 'Astuti',
        email: 'dewi.astuti@example.com',
        birthDate: new Date('1990-03-27'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 58,
        username: 'eko.ramadhan',
        firstName: 'Eko',
        lastName: 'Ramadhan',
        email: 'eko.ramadhan@example.com',
        birthDate: new Date('1987-04-28'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 59,
        username: 'rini.sari',
        firstName: 'Rini',
        lastName: 'Sari',
        email: 'rini.sari@example.com',
        birthDate: new Date('1992-05-29'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 60,
        username: 'budi.kurniawan',
        firstName: 'Budi',
        lastName: 'Kurniawan',
        email: 'budi.kurniawan@example.com',
        birthDate: new Date('1985-06-30'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 61,
        username: 'nisa.sari',
        firstName: 'Nisa',
        lastName: 'Sari',
        email: 'nisa.sari@example.com',
        birthDate: new Date('1986-07-01'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 62,
        username: 'agus.permana',
        firstName: 'Agus',
        lastName: 'Permana',
        email: 'agus.permana@example.com',
        birthDate: new Date('1990-08-02'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 63,
        username: 'fitri.wati',
        firstName: 'Fitri',
        lastName: 'Wati',
        email: 'fitri.wati@example.com',
        birthDate: new Date('1985-09-03'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 64,
        username: 'surya.putra',
        firstName: 'Surya',
        lastName: 'Putra',
        email: 'surya.putra@example.com',
        birthDate: new Date('1989-10-04'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 65,
        username: 'nina.sari',
        firstName: 'Nina',
        lastName: 'Sari',
        email: 'nina.sari@example.com',
        birthDate: new Date('1991-11-05'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 66,
        username: 'adi.wibowo',
        firstName: 'Adi',
        lastName: 'Wibowo',
        email: 'adi.wibowo@example.com',
        birthDate: new Date('1988-12-06'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 67,
        username: 'dewi.ramadhani',
        firstName: 'Dewi',
        lastName: 'Ramadhani',
        email: 'dewi.ramadhani@example.com',
        birthDate: new Date('1990-01-07'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 68,
        username: 'eko.purnomo',
        firstName: 'Eko',
        lastName: 'Purnomo',
        email: 'eko.purnomo@example.com',
        birthDate: new Date('1987-02-08'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 69,
        username: 'rini.sari',
        firstName: 'Rini',
        lastName: 'Sari',
        email: 'rini.sari@example.com',
        birthDate: new Date('1992-03-09'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 70,
        username: 'budi.santoso3',
        firstName: 'Budi',
        lastName: 'Santoso',
        email: 'budi.santoso3@example.com',
        birthDate: new Date('1985-04-10'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 71,
        username: 'novi.astuti',
        firstName: 'Novi',
        lastName: 'Astuti',
        email: 'novi.astuti@example.com',
        birthDate: new Date('1986-05-11'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 72,
        username: 'agus.ramadhan',
        firstName: 'Agus',
        lastName: 'Ramadhan',
        email: 'agus.ramadhan@example.com',
        birthDate: new Date('1990-06-22'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 73,
        username: 'fitri.susanto',
        firstName: 'Fitri',
        lastName: 'Susanto',
        email: 'fitri.susanto@example.com',
        birthDate: new Date('1985-07-13'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 74,
        username: 'surya.prabowo',
        firstName: 'Surya',
        lastName: 'Prabowo',
        email: 'surya.prabowo@example.com',
        birthDate: new Date('1989-08-24'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 75,
        username: 'nina.kusuma',
        firstName: 'Nina',
        lastName: 'Kusuma',
        email: 'nina.kusuma@example.com',
        birthDate: new Date('1991-09-15'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 76,
        username: 'adi.widodo',
        firstName: 'Adi',
        lastName: 'Widodo',
        email: 'adi.widodo@example.com',
        birthDate: new Date('1988-10-26'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 77,
        username: 'dewi.sari',
        firstName: 'Dewi',
        lastName: 'Sari',
        email: 'dewi.sari@example.com',
        birthDate: new Date('1990-11-17'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 78,
        username: 'eko.ramadhani',
        firstName: 'Eko',
        lastName: 'Ramadhani',
        email: 'eko.ramadhani@example.com',
        birthDate: new Date('1987-12-28'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 79,
        username: 'rini.sari',
        firstName: 'Rini',
        lastName: 'Sari',
        email: 'rini.sari@example.com',
        birthDate: new Date('1992-01-19'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 80,
        username: 'budi.kusuma',
        firstName: 'Budi',
        lastName: 'Kusuma',
        email: 'budi.kusuma@example.com',
        birthDate: new Date('1985-02-20'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 81,
        username: 'novi.santoso',
        firstName: 'Novi',
        lastName: 'Santoso',
        email: 'novi.santoso@example.com',
        birthDate: new Date('1986-03-21'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 82,
        username: 'agus.kurniawan',
        firstName: 'Agus',
        lastName: 'Kurniawan',
        email: 'agus.kurniawan@example.com',
        birthDate: new Date('1990-04-22'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 83,
        username: 'fitri.rahayu',
        firstName: 'Fitri',
        lastName: 'Rahayu',
        email: 'fitri.rahayu@example.com',
        birthDate: new Date('1985-05-23'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 84,
        username: 'surya.susilo',
        firstName: 'Surya',
        lastName: 'Susilo',
        email: 'surya.susilo@example.com',
        birthDate: new Date('1989-06-24'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 85,
        username: 'nina.wati',
        firstName: 'Nina',
        lastName: 'Wati',
        email: 'nina.wati@example.com',
        birthDate: new Date('1991-07-25'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 86,
        username: 'adi.santoso',
        firstName: 'Adi',
        lastName: 'Santoso',
        email: 'adi.santoso@example.com',
        birthDate: new Date('1988-08-26'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 87,
        username: 'dewi.purnomo',
        firstName: 'Dewi',
        lastName: 'Purnomo',
        email: 'dewi.purnomo@example.com',
        birthDate: new Date('1990-09-27'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 88,
        username: 'eko.sari',
        firstName: 'Eko',
        lastName: 'Sari',
        email: 'eko.sari@example.com',
        birthDate: new Date('1987-10-28'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 89,
        username: 'rini.wibowo',
        firstName: 'Rini',
        lastName: 'Wibowo',
        email: 'rini.wibowo@example.com',
        birthDate: new Date('1992-11-29'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 90,
        username: 'budi.ramadhan',
        firstName: 'Budi',
        lastName: 'Ramadhan',
        email: 'budi.ramadhan@example.com',
        birthDate: new Date('1985-12-30'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
    {
        id: 91,
        username: 'novi.permana',
        firstName: 'Novi',
        lastName: 'Permana',
        email: 'novi.permana@example.com',
        birthDate: new Date('1986-01-11'),
        basicSalary: 5300000,
        status: 'Active',
        group: 'Retail Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 92,
        username: 'agus.wijaya',
        firstName: 'Agus',
        lastName: 'Wijaya',
        email: 'agus.wijaya@example.com',
        birthDate: new Date('1990-02-12'),
        basicSalary: 5400000,
        status: 'Active',
        group: 'Corporate Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 93,
        username: 'fitri.wijaya',
        firstName: 'Fitri',
        lastName: 'Wijaya',
        email: 'fitri.wijaya@example.com',
        birthDate: new Date('1985-03-13'),
        basicSalary: 5500000,
        status: 'Active',
        group: 'Investment Banking',
        description: new Date('2023-06-01')
    },
    {
        id: 94,
        username: 'surya.permana',
        firstName: 'Surya',
        lastName: 'Permana',
        email: 'surya.permana@example.com',
        birthDate: new Date('1989-04-14'),
        basicSalary: 5600000,
        status: 'Active',
        group: 'Wealth Management',
        description: new Date('2023-06-01')
    },
    {
        id: 95,
        username: 'nina.widodo',
        firstName: 'Nina',
        lastName: 'Widodo',
        email: 'nina.widodo@example.com',
        birthDate: new Date('1991-05-15'),
        basicSalary: 5700000,
        status: 'Active',
        group: 'Risk Management',
        description: new Date('2023-06-01')
    },
    {
        id: 96,
        username: 'adi.putra',
        firstName: 'Adi',
        lastName: 'Putra',
        email: 'adi.putra@example.com',
        birthDate: new Date('1988-06-16'),
        basicSalary: 5800000,
        status: 'Active',
        group: 'Operations',
        description: new Date('2023-06-01')
    },
    {
        id: 97,
        username: 'dewi.ramadhan',
        firstName: 'Dewi',
        lastName: 'Ramadhan',
        email: 'dewi.ramadhan@example.com',
        birthDate: new Date('1990-07-17'),
        basicSalary: 5900000,
        status: 'Active',
        group: 'Compliance',
        description: new Date('2023-06-01')
    },
    {
        id: 98,
        username: 'eko.susanto',
        firstName: 'Eko',
        lastName: 'Susanto',
        email: 'eko.susanto@example.com',
        birthDate: new Date('1987-08-18'),
        basicSalary: 6000000,
        status: 'Active',
        group: 'Technology',
        description: new Date('2023-06-01')
    },
    {
        id: 99,
        username: 'rini.permana',
        firstName: 'Rini',
        lastName: 'Permana',
        email: 'rini.permana@example.com',
        birthDate: new Date('1992-09-19'),
        basicSalary: 6100000,
        status: 'Active',
        group: 'Human Resources',
        description: new Date('2023-06-01')
    },
    {
        id: 100,
        username: 'budi.wijaya',
        firstName: 'Budi',
        lastName: 'Wijaya',
        email: 'budi.wijaya@example.com',
        birthDate: new Date('1985-10-20'),
        basicSalary: 6200000,
        status: 'Active',
        group: 'Marketing',
        description: new Date('2023-06-01')
    },
]